name: todo-frontend-dev

services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend-dev # This will name the container todo-frontend-dev
