name: todo-app-dev

services:
  frontend-dev:
    container_name: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    env_file:
      - .env.development

  backend-dev:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - .env.development
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: todo-mongo-dev
    image: mongo
    ports:
      - "${MONGO_PORT:-3456}:27017"
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    env_file:
      - .env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root1234}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-todo-app}

  redis:
    container_name: todo-redis-dev
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./todo-backend/redis_data:/data
    env_file:
      - .env.development
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis1234}

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend-dev
      - backend-dev

volumes:
  mongo_data:
  redis_data:
