name: todo-backend-dev
services:
  mongo:
    container_name: todo-mongo-dev
    image: mongo
    ports:
      - 3456:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
      MONGO_INITDB_DATABASE: todo-app

volumes:
  mongo_data:
